apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
      tier: action
  template:
    metadata:
      labels:
        app: rasa
        tier: action
    spec:
      containers:
      - name: rasa-action
        image: saifulmalook/action
        ports:
        - containerPort: 5055
          name: rasa-action
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rasa
      tier: server
  template:
    metadata:
      labels:
        app: rasa
        tier: server
    spec:
      containers:
      - name: rasa-server
        image: codife/test-rasa
        ports:
        - containerPort: 8080
          name: rasa-server
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: rasa
    tier: server
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-action
spec:
  type: ClusterIP
  ports:
  - name: action
    port: 5055
    targetPort: 5055
  selector:
    app: rasa
    tier: action

